# Grafana Datasource Provisioning
# Story E1.2 Phase 1.5
# Auto-Konfiguration der Prometheus Datasource

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s
    version: 1

